### ISSUE TITLE
Expand to 🇩🇪🇨🇭🇦🇹 German-speaking countries

### ISSUE THREAD

**Issue by caugner** [osmontrouge/caresteouvert#149]
## Requirements

- [x] You are a team of at least 2 people experienced with OpenStreetMap (see below)
- [x] Translate the app via transifex with your country languages
- [x] Translate some content of the blog (see https://github.com/bleibtoffen/caresteouvert-de/issues/2)
- [x] Start gathering data about chains (see https://github.com/bleibtoffen/caresteouvert-de/issues/6)
- [ ] Organise media coverage (see https://github.com/bleibtoffen/caresteouvert-de/issues/37)
- [ ] **New**: Organise notes handling (see https://github.com/bleibtoffen/caresteouvert-de/issues/35)

## Team

See also: https://lists.openstreetmap.org/pipermail/talk-de/2020-April/116708.html

* @caugner
* @jens1o
* @giggls
* @ChristineKarch
* @datendelphin
* @chnuessli
* (Let me know if you're interested.)

## Localized domain name

* `bleibtoffen.at` for Austria
* `bleibtoffen.ch` for Switzerland
* `bleibtoffen.de` for Germany
* `bleibtoffen.org` for static content (blog etc.)

## What shops are open or closed?

See: https://github.com/caugner/bleibtoffen-de/blob/master/laender.csv

## What should be done in the category list?

See: https://github.com/caugner/bleibtoffen-de/blob/master/laender.csv (Filter: `all`)

## Related projects

* [lokalwirkt](https://lokalwirkt.de/store-map) is a regional initiative in Nordrhein-Westfalen to update opening hours.
* [wirhabenauf](https://wirhabenauf.de/) shows an OSM-based map and allows users to add/update locations (independently from OpenStreetMap).

**Comment by caugner** [comment]
@jens1o Perfect, Jens, I have added you to the team list.

:de: Aktuelle Aufgaben:
* Für Bundesländer herausfinden, welche Orte dort geöffnet bzw. geschlossen sind? Bei der Zuordnung von Orten zu OSM-Tags fand ich diese Liste sehr hilfreich: https://wiki.openstreetmap.org/wiki/Germany/Shops
* Blog-Artikel übersetzen: TO BE COMPLETED

**Comment by caugner** [comment]
:de: Die Bundesländer sollten wir wohl nach Einwohnerzahl priorisiert abarbeiten:

- [ ] Nordrhein-Westfalen
- [ ] Bayern
- [ ] Baden-Württemberg
- [ ] Niedersachsen
- [ ] Hessen
- [ ] Sachsen
- [ ] Rheinland-Pfalz
- [x] Berlin
- [ ] Schleswig-Holstein
- [ ] Brandenburg
- [ ] Sachsen-Anhalt
- [ ] Thüringen
- [ ] Hamburg
- [ ] Mecklenburg-Vorpommern
- [ ] Saarland
- [ ] Bremen

**Comment by caugner** [comment]
@giggls You seem to be interested as well. Mind if I add you to the team list?

**Comment by giggls** [comment]
Would be good if the above document could be edited by others. Should we open our own repository for this.
Subdomain of openstreetmap.de is no problem as is Webspace on the fossgis Project-Server.

Legislation for Baden-Württemberg is available here:
https://corona.karlsruhe.de/content/downloads/200328_CoronaVO_Konsolidierte_Fassung.pdf

If you open a repo I will send you a patch.

**Comment by caugner** [comment]
@giggls Here we go: https://github.com/caugner/caresteouvert-de

Will move the information from the issue there shortly.

**Comment by caugner** [comment]
@hbruch has [pointed out](https://lists.openstreetmap.org/pipermail/talk-de/2020-April/116710.html) a similar project: https://github.com/binary-butterfly/shared-delivery

**Comment by giggls** [comment]
I am a little bit sceptical about maintaining an external database for this.

**Comment by caugner** [comment]
Yes, as far as I can see, both lokalwirkt and wirhabenauf use their own database to store the updated opening times.

**Comment by giggls** [comment]
French Software does not, right?

**Comment by caugner** [comment]
Correct, see here for the automated changes based on user feedback:
https://www.openstreetmap.org/user/CaResteOuvert_visitor/history

**Comment by giggls** [comment]
OK better approach IMO.

**Comment by caugner** [comment]
Blocked by #106.

**Comment by caugner** [comment]
@francois2metz Let me know if you need any further input from us.

I have added Austria and Switzerland to the description, since we already have Swiss chains recorded and Austria will probably follow soon.

Showing the same categories as France is not a problem for us, because the lockdown rules are very similar and it's easier to figure out required customizations once the German team can try out the tool themselves.

**Comment by francois2metz** [comment]
Thanks for the update! Once the planet import is ready we'll enable Germany first.

We'll keep you updated once we are ready.

**Comment by chnuessli** [comment]
Hallo Claas
Bin dabei, habe bereits einen pull-request platziert.
Grüsse aus der Schweiz

**Comment by caugner** [comment]
@chnuessli Danke, habe dich eingetragen und zur [Organisation](https://github.com/bleibtoffen) eingeladen.

**Comment by caugner** [comment]
We are now live:

* :austria: https://www.bleibtoffen.at/
* :switzerland: https://www.bleibtoffen.ch/
* :de: https://www.bleibtoffen.de/

See https://github.com/bleibtoffen/caresteouvert-de/issues for issues related to AT/CH/DE.

**Comment by chnuessli** [comment]
Yes, cool!

**Comment by wetneb** [comment]
The map tiles need to be adapted as well, at the moment they only work in France.
https://github.com/bleibtoffen/bleibtoffen/issues/103
